packages: []

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - tar # patch vulnerable version immediately
  - "@isaacs/brace-expansion"

nodeLinker: hoisted

overrides:
  tar: 7.5.8
  lodash-es: 4.17.23
  fast-xml-parser: 5.3.6
saveExact: true
