packages: []

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - tar
  - minimatch

nodeLinker: hoisted

overrides:
  tar: 7.5.8
  lodash-es: 4.17.23
  fast-xml-parser: 5.3.6
  minimatch: 10.2.3
  storybook: 10.2.10

saveExact: true
