packages: []

minimumReleaseAge: 4320

nodeLinker: hoisted

overrides:
  brace-expansion: 2.0.2
  devalue: 5.6.2
  diff: 8.0.3
  glob: 11.1.0
  h3: 1.15.5
  node-forge: 1.3.2
  nwsapi: 2.2.20
  tar: 7.5.3

saveExact: true
