packages: []

overrides:
  "esbuild": "0.28.1"
  "vite-plugin-checker": "0.13.0"

allowBuilds:
  "@parcel/watcher": true
  "@sentry/cli": false
  core-js: false
  esbuild: true
  protobufjs: false
  vue-demi: false

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@digitalservicebund/ris-ui"
  - "@playwright/test@1.61.1"
  - playwright-core@1.61.1
  - playwright@1.61.1

publicHoistPattern:
  - "vue"
  - "vite"

savePrefix: ""
