packages: []

allowBuilds:
  "@parcel/watcher": true
  "@sentry/cli": false
  core-js: false
  esbuild: true
  protobufjs: false
  vue-demi: false

minimumReleaseAge: 4320

publicHoistPattern:
  - "vue"
  - "vite"

savePrefix: ""

overrides:
  nanoid: 3.3.17
  js-yaml: 4.3.1

minimumReleaseAgeExclude:
  - "@digitalservicebund/ris-ui@4.7.0"
