packages: []

allowBuilds:
  "@parcel/watcher": true
  "@sentry/cli": false
  core-js: false
  esbuild: true
  protobufjs: false
  vue-demi: false

overrides:
  brace-expansion: 5.0.8

minimumReleaseAge: 4320

publicHoistPattern:
  - "vue"
  - "vite"

savePrefix: ""

minimumReleaseAgeExclude:
  - '@digitalservicebund/ris-ui@4.6.1'
