# Redirect all temp paths to /tmp so nginx can  starts with a read onlu
# filesystem without trying to create those directories (which would fail)
client_body_temp_path /tmp;
proxy_temp_path       /tmp;
fastcgi_temp_path     /tmp;
uwsgi_temp_path       /tmp;
scgi_temp_path        /tmp;

server {
    listen       8080;
    server_name  _;
    error_page 404 /404.html;

    location / {
        root   /usr/share/nginx/html;

        # Avoid problems with nginx default redirects that add trailing slashes.
        absolute_redirect off;
    }
}