FROM gradle:9.6.1-jdk21@sha256:9795f8c9009a7de6adea522b907c9aadc38fe7c313874112c2b696c8e70b0303 AS backend-builder
WORKDIR /app
COPY . /app

RUN --mount=type=secret,id=GH_PACKAGES_REPOSITORY_USER \
    --mount=type=secret,id=GH_PACKAGES_REPOSITORY_TOKEN \
    export GH_PACKAGES_REPOSITORY_USER=$(cat /run/secrets/GH_PACKAGES_REPOSITORY_USER) && \
    export GH_PACKAGES_REPOSITORY_TOKEN=$(cat /run/secrets/GH_PACKAGES_REPOSITORY_TOKEN) && \
    ./gradlew build -x integrationTest -x test -x spotlessCheck

FROM cgr.dev/chainguard/jre@sha256:76398cee8378a3483096775e909e6c4b5736782823f1bae32d4c8ffc8a84e052
ARG SENTRY_RELEASE
COPY --from=backend-builder /app/build/libs/ris-search-*.jar /app/app.jar
EXPOSE 8090
ENV SENTRY_RELEASE=${SENTRY_RELEASE}
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
