FROM gradle:9.6.0-jdk21@sha256:6b71d4d40e45200709c178ca0ab10125e1d99e6e44dec6bcbabd0a3371f8e650 AS backend-builder
WORKDIR /app
COPY . /app

RUN --mount=type=secret,id=GH_PACKAGES_REPOSITORY_USER \
    --mount=type=secret,id=GH_PACKAGES_REPOSITORY_TOKEN \
    export GH_PACKAGES_REPOSITORY_USER=$(cat /run/secrets/GH_PACKAGES_REPOSITORY_USER) && \
    export GH_PACKAGES_REPOSITORY_TOKEN=$(cat /run/secrets/GH_PACKAGES_REPOSITORY_TOKEN) && \
    ./gradlew build -x integrationTest -x test -x spotlessCheck

FROM cgr.dev/chainguard/jre@sha256:6dea879333f679e7865ebfc49760a85ccc12f6625da87fd591f04a35bba11117
ARG SENTRY_RELEASE
COPY --from=backend-builder /app/build/libs/ris-search-*.jar /app/app.jar
EXPOSE 8090
ENV SENTRY_RELEASE=${SENTRY_RELEASE}
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
