server {
    listen       8080;
    server_name  _;
    error_page 404 /404.html;

    location / {
        root   /usr/share/nginx/html;

        # Avoid problems with nginx default redirects that add trailing slashes.
        absolute_redirect off;
    }
}