/**
 * This file was auto-generated by openapi-typescript. Do not make direct
 * changes to the file.
 */

export interface paths {
  "/v1/statistics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getStatisticsData"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/literature": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List and search literature
     *
     * The endpoint returns a list of literature from our database. The list is
     * paginated and can be filtered and sorted.
     */
    get: operations["searchAndFilter"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/literature/{documentNumber}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Literature metadata
     *
     * The endpoint returns the metadata of a single literature from our
     * database.
     */
    get: operations["getLiteratureMetadata"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/literature/{documentNumber}.xml": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Literature XML
     *
     * Returns a literature item as XML. This content is used as a source for
     * the HTML endpoint.
     */
    get: operations["getLiteratureAsXml"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/literature/{documentNumber}.html": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Literature HTML
     *
     * Renders and returns a literature item as HTML.
     */
    get: operations["getLiteratureAsHtml"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/literature/changelog": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Literature changelog
     *
     * Returns references of document changes that occurred in between two
     * points in time.
     */
    get: operations["getChangelogs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/legislation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List and search legislation
     *
     * List all legislation in our database with support for filtering and
     * pagination.
     *
     * ## Example 1
     *
     * Get all legislation containing the tokens :` Gesetz`, `über`,`das`,
     * `Verfahren`, `bei`, `sonstigen` and `Änderungen`.
     *
     * ```http
     * GET /v1/legislation?searchTerm=Gesetz%20über%20das%20Verfahren%20bei%20sonstigen%20Änderungen
     * ```
     *
     * The API will return only the legislation that contains all these terms.
     * Please note that in practice very common tokens such as `das` are ignored
     * (please see <a
     * href="https://en.wikipedia.org/wiki/Stop_word">https://en.wikipedia.org/wiki/Stop_word</a>
     * for more details).
     *
     * ## Example 2
     *
     * Get all legislation containing the tokens :` Gesetz` and `über` and were
     * valid on 2020-01-01
     *
     * ```http
     * GET /v1/legislation?temporalCoverageFrom=2020-01-01&temporalCoverageTo=2020-01-01&searchTerm=Gesetz%20über
     * ```
     *
     * This example can be used to only return currently valid legislation by
     * replacing 2020-01-01 with today's date.
     *
     * ## Example 3
     *
     * Get all of the legislation that belong to the work eli
     * `eli/bund/bgbl-1/1979/s1325`
     *
     * ```http
     * GET /v1/legislation?eli=eli/bund/bgbl-1/1979/s1325
     * ```
     */
    get: operations["searchAndFilter_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/legislation/eli/{jurisdiction}/{agent}/{year}/{naturalIdentifier}/{pointInTime}/{version}/{language}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Work and expression-level metadata
     *
     * Returns metadata of a legislation item.
     */
    get: operations["getLegislation"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/legislation/eli/{jurisdiction}/{agent}/{year}/{naturalIdentifier}/{pointInTime}/{version}/{language}/{pointInTimeManifestation}/{subtype}/{articleEid}.html": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Manifestation article (§) HTML
     *
     * Returns a specific article (§) of particular manifestation of a piece of
     * legislation, converted to HTML.
     */
    get: operations["getLegislationArticleAsHtml"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/legislation/eli/{jurisdiction}/{agent}/{year}/{naturalIdentifier}/{pointInTime}/{version}/{language}/{pointInTimeManifestation}/{subtype}.xml": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Manifestation XML
     *
     * Returns a particular manifestation of a piece of legislation in XML
     * format.
     *
     * ## Example
     *
     * Download the LegalDocML format for the piece of legislation with a
     * manifestation eli of
     * `eli/bund/bgbl-1/1979/s1325/2020-06-19/2/deu/2020-06-19/regelungstext-1.xml`
     *
     * ```http
     * GET /v1/eli/bund/bgbl-1/1979/s1325/2020-06-19/2/deu/2020-06-19/regelungstext-1.xml
     * ```
     */
    get: operations["getLegislationSubtypeAsXml"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/legislation/eli/{jurisdiction}/{agent}/{year}/{naturalIdentifier}/{pointInTime}/{version}/{language}/{pointInTimeManifestation}/{subtype}.html": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Manifestation HTML
     *
     * Returns a particular manifestation of a piece of legislation, converted
     * to HTML.
     */
    get: operations["getLegislationSubtypeAsHtml"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/legislation/eli/{jurisdiction}/{agent}/{year}/{naturalIdentifier}/{pointInTime}/{version}/{language}/{pointInTimeManifestation}/{name}.{extension}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Manifestation resource
     *
     * Returns a specific resource of a particular manifestation of a piece of
     * legislation.
     */
    get: operations["getFile"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/legislation/eli/{jurisdiction}/{agent}/{year}/{naturalIdentifier}/{pointInTime}/{version}/{language}/{pointInTimeManifestation}.zip": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Manifestation ZIP (XML and attachments)
     *
     * Returns a particular manifestation of a piece of legislation, including
     * attachments, as a ZIP archive. Note the omission of the subtype path
     * parameter.
     */
    get: operations["getLegislationSubtypeAsZip"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/legislation/changelog": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Legislation changelog
     *
     * Returns references of document changes that occurred in between two
     * points in time.
     */
    get: operations["getChangelogs_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/document": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Global search / list
     *
     * This endpoint can be used to search for documents across different
     * document kinds. Currently we support case law, legislation and literature
     * document kinds. The endpoint provides a paginated response with up to
     * 10,000 results with at most 100 results per page. The searchTerm
     * parameter searches across multiple fields of a document at the same time.
     * The fields searched depend on the document kind. See the filters guide
     * for more information. Default sorting is by relevance from most relevant
     * to least relevant. Multiple factors are combined to boost the most
     * relevant documents to the top of the result list. Additionally, sorting
     * by date is possible by setting the sort query parameter to date.
     */
    get: operations["searchAndFilter_2"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/document/lucene-search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Advanced search using Lucene query syntax */
    get: operations["search"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/document/lucene-search/literature": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Advanced search using Lucene query syntax */
    get: operations["literatureSearch"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/document/lucene-search/legislation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Advanced search using Lucene query syntax */
    get: operations["searchLegislation"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/document/lucene-search/case-law": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Advanced search using Lucene query syntax */
    get: operations["caseLawSearch"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/document/lucene-search/administrative-directive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Advanced search using Lucene query syntax */
    get: operations["literatureSearch_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/case-law": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List and search decisions
     *
     * The endpoint returns a list of decisions from our database. The list is
     * paginated and can be filtered and sorted.
     */
    get: operations["searchAndFilter_3"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/case-law/{documentNumber}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Decision metadata
     *
     * The endpoint returns a single decision from our database.
     */
    get: operations["getCaseLaw"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/case-law/{documentNumber}/{name}.{extension}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Caselaw resource
     *
     * Returns a specific resource of a particular caselaw.
     */
    get: operations["getImage"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/case-law/{documentNumber}.zip": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Decision ZIP (XML and attachments)
     *
     * Returns a case law decision, including attachments, as a ZIP archive.
     */
    get: operations["getCaseLawDocumentationUnitAsZip"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/case-law/{documentNumber}.xml": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Decision XML
     *
     * Returns a case law decision as XML. This content is used as a source for
     * the HTML endpoint.
     */
    get: operations["getCaseLawDocumentationUnitAsXml"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/case-law/{documentNumber}.html": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Decision HTML
     *
     * Renders and returns a case law decision as HTML.
     */
    get: operations["getCaseLawDocumentationUnitAsHtml"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/case-law/courts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List courts
     *
     * Lists courts with long and short name and number of associated decisions.
     * The prefix parameter may be used to filter this list. Only includes
     * courts whose decisions have been published in this database.
     */
    get: operations["getCourts"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/case-law/changelog": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Caselaw changelog
     *
     * Returns references of document changes that occurred in between two
     * points in time.
     */
    get: operations["getChangelogs_2"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/bulk-zip-links": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getBulkZipLinks"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/administrative-directive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List and search administrative directives
     *
     * The endpoint returns a list of administrative directives from our
     * database. The list is paginated and can be filtered and sorted.
     */
    get: operations["searchAndFilter_4"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/administrative-directive/{documentNumber}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Administrative directive metadata
     *
     * The endpoint returns the metadata of a single administrative directive
     * from our database.
     */
    get: operations["getAdministrativeDirectiveMetadata"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/administrative-directive/{documentNumber}.xml": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Administrative directive XML
     *
     * Returns an administrative directive item as XML. This content is used as
     * a source for the HTML endpoint.
     */
    get: operations["getAdministrativeDirectiveAsXml"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/administrative-directive/{documentNumber}.html": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Administrative directive HTML
     *
     * Renders and returns an administrative directive as HTML.
     */
    get: operations["getAdministrativeDirectiveAsHtml"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/administrative-directive/changelog": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Administrative Directive changelog
     *
     * Returns references of document changes that occurred in between two
     * points in time.
     */
    get: operations["getChangelogs_3"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    StatisticsApiSchema: {
      legislation: components["schemas"]["StatisticsCountSchema"];
      "case-law": components["schemas"]["StatisticsCountSchema"];
      literature: components["schemas"]["StatisticsCountSchema"];
      "administrative-directive": components["schemas"]["StatisticsCountSchema"];
    };
    StatisticsCountSchema: {
      /** Format: int64 */
      count: number;
    };
    CollectionSchemaSearchMemberSchemaLiteratureSearchSchema: {
      /**
       * @example
       *   hydra: Collection;
       */
      "@type"?: string;
      /**
       * @example
       *   /v1/document?pageIndex=0&size=5
       */
      "@id": string;
      /**
       * Format: int64
       *
       * @example
       *   1;
       */
      totalItems: number;
      member: components["schemas"]["SearchMemberSchemaLiteratureSearchSchema"][];
      view: components["schemas"]["PartialCollectionViewSchema"];
    };
    LiteratureEncodingSchema: {
      /**
       * @example
       *   MediaObject;
       */
      "@type"?: string;
      "@id": string;
      contentUrl: string;
      /**
       * @example
       *   text / html;
       */
      encodingFormat: string;
      /**
       * @example
       *   de;
       */
      inLanguage: string;
    };
    LiteratureSearchSchema: {
      "@type": "LiteratureSearchSchema";
    } & (Omit<components["schemas"]["AbstractDocumentSchema"], "@type"> & {
      /**
       * @example
       *   Literature;
       */
      "@type"?: string;
      /**
       * @example
       *   KALU000000000;
       */
      "@id": string;
      /**
       * @example
       *   de;
       */
      inLanguage: string;
      /**
       * Dokumentnummer
       *
       * @example
       *   KALU000000000;
       */
      documentNumber: string;
      /**
       * Veröffentlichungsjahre
       *
       * @example
       *   [2014, 2024 - 09];
       */
      yearsOfPublication: string[];
      /**
       * Format: date
       *
       * Erstes Veröffentlichungsdatum
       *
       * @example
       *   2014 - 01 - 01;
       */
      firstPublicationDate: string;
      /**
       * Dokumenttypen
       *
       * @example
       *   ["Auf"];
       */
      documentTypes: string[];
      /**
       * Unselbstständige Fundstellen
       *
       * @example
       *   ["BUV, 1982, 123-123"];
       */
      dependentReferences: string[];
      /**
       * Selbstständige Fundstellen
       *
       * @example
       *   ["50 Jahre Betriebs-Berater, 1987, 123-456"];
       */
      independentReferences: string[];
      /** Haupttitel */
      headline?: string;
      /** Dokumentarischer Titel */
      alternativeHeadline?: string;
      /**
       * Autoren
       *
       * @example
       *   ["Musterfrau, Sabine"];
       */
      authors: string[];
      /**
       * Mitarbeiter
       *
       * @example
       *   ["Mustermann, Max"];
       */
      collaborators: string[];
      /** Kurzreferat */
      shortReport?: string;
      /** Gliederung */
      outline?: string;
      /**
       * Literaturtyp
       *
       * @example
       *   ["sli", "uli"];
       */
      literatureType: string;
      encoding: components["schemas"]["LiteratureEncodingSchema"][];
    });
    PartialCollectionViewSchema: {
      /**
       * @example
       *   hydra: PartialCollectionView;
       */
      "@type"?: string;
      first?: string;
      previous?: string;
      next?: string;
      last?: string;
    };
    SearchMemberSchemaLiteratureSearchSchema: {
      /**
       * @example
       *   SearchResult;
       */
      "@type"?: string;
      item: components["schemas"]["LiteratureSearchSchema"];
      textMatches: components["schemas"]["TextMatchSchema"][];
    };
    TextMatchSchema: {
      /**
       * @example
       *   SearchResultMatch;
       */
      "@type"?: string;
      name: string;
      text: string;
      location?: string | null;
    };
    LiteratureSchema: {
      /**
       * @example
       *   Literature;
       */
      "@type"?: string;
      /**
       * @example
       *   KALU000000000;
       */
      "@id": string;
      /**
       * @example
       *   de;
       */
      inLanguage: string;
      /**
       * Dokumentnummer
       *
       * @example
       *   KALU000000000;
       */
      documentNumber: string;
      /**
       * Veröffentlichungsjahre
       *
       * @example
       *   [2014, 2024 - 09];
       */
      yearsOfPublication: string[];
      /**
       * Dokumenttypen
       *
       * @example
       *   ["Auf"];
       */
      documentTypes: string[];
      /**
       * Unselbstständige Fundstellen
       *
       * @example
       *   ["BUV, 1982, 123-123"];
       */
      dependentReferences: string[];
      /**
       * Selbstständige Fundstellen
       *
       * @example
       *   ["50 Jahre Betriebs-Berater, 1987, 123-456"];
       */
      independentReferences: string[];
      /**
       * Norm Verweise
       *
       * @example
       *   ["GG, Art 6 Abs 2 S 1, 1949-05-23"];
       */
      normReferences: string[];
      /** Haupttitel */
      headline?: string;
      /** Zusätze zum Haupttitel */
      headlineAdditions?: string;
      /** Dokumentarischer Titel */
      alternativeHeadline?: string;
      /** Ausgabe */
      edition?: string;
      /** Bestellnummer */
      internationalIdentifiers: string[];
      /**
       * Autoren
       *
       * @example
       *   ["Musterfrau, Sabine"];
       */
      authors: string[];
      /**
       * Mitarbeiter
       *
       * @example
       *   ["Mustermann, Max"];
       */
      collaborators: string[];
      /** Bearbeiter */
      editors: string[];
      /** Begründer */
      founder: string[];
      /** Herausgeber (Person) */
      publishers: string[];
      /** Herausgeber (Institution) */
      publisherOrganizations: string[];
      /** Verlag */
      publishingHouses: string[];
      /**
       * Sprachen
       *
       * @example
       *   ["deu", "eng"];
       */
      languages: string[];
      /**
       * Urheber
       *
       * @example
       *   ["DGB"];
       */
      originators: string[];
      /**
       * Kongressvermerke
       *
       * @example
       *   ["Nationaler Beispiel Kongress, 2024, Berlin, GER"];
       */
      conferenceNotes: string[];
      /** Kurzreferat */
      shortReport?: string;
      /** Gliederung */
      outline?: string;
      /** Hochschulvermerk */
      universityNotes: string[];
      /** Teilbaende */
      volumes: string[];
      /**
       * Literaturtyp
       *
       * @example
       *   ["sli", "uli"];
       */
      literatureType: string;
      encoding: components["schemas"]["LiteratureEncodingSchema"][];
    };
    ChangelogChangedDocument: {
      /** Unique identifier of the document */
      "@id": string;
      /** Type of the document */
      "@type": string;
      contentUrl: string;
    };
    ChangelogDeletedDocument: {
      /** Unique identifier of the document */
      "@id": string;
      /** Type of the document */
      "@type": string;
    };
    ChangelogResponse: {
      "@context"?: {
        [key: string]: unknown;
      };
      /** Set of changed documents */
      changed: components["schemas"]["ChangelogChangedDocument"][];
      /** Set of deleted documents */
      deleted: components["schemas"]["ChangelogDeletedDocument"][];
      /** Flag to communicate that the whole storage got rebuilt */
      allChanged: boolean;
    };
    CollectionSchemaSearchMemberSchemaLegislationExpressionSearchSchema: {
      /**
       * @example
       *   hydra: Collection;
       */
      "@type"?: string;
      /**
       * @example
       *   /v1/document?pageIndex=0&size=5
       */
      "@id": string;
      /**
       * Format: int64
       *
       * @example
       *   1;
       */
      totalItems: number;
      member: components["schemas"]["SearchMemberSchemaLegislationExpressionSearchSchema"][];
      view: components["schemas"]["PartialCollectionViewSchema"];
    };
    /** A legislation expression and references to its manifestations. */
    LegislationExpressionSearchSchema: {
      "@type": "LegislationExpressionSearchSchema";
    } & (Omit<components["schemas"]["AbstractDocumentSchema"], "@type"> & {
      /**
       * @example
       *   Legislation;
       */
      "@type"?: string;
      /**
       * @example
       *   /v1/legislation/eli/bund/bgbl-1/1975/s1760/1998-01-29/10/deu
       */
      "@id": string;
      /**
       * Amtliche Langüberschrift
       *
       * @example
       *   Verordnung über Kakao und Kakaoerzeugnisse
       */
      name: string;
      /**
       * @example
       *   eli / bund / bgbl - 1 / 1975 / s1760 / 1998 - 01 - 29 / 10 / deu;
       */
      legislationIdentifier: string;
      /** The work the expression is based on */
      exampleOfWork: components["schemas"]["LegislationWorkSchema"];
      /**
       * Textual string indicating a time period in [ISO 8601 time interval
       * format](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals)
       *
       * @example
       *   1998-02-06/..
       */
      temporalCoverage: string;
      /**
       * Amtliche Buchstabenabkürzung, if it exists. Otherwise ris-abkuerzung.
       *
       * @example
       *   KakaoV 2003
       */
      abbreviation?: string;
      /**
       * Amtliche Kurzüberschrift
       *
       * @example
       *   Kakaoverordnung;
       */
      alternateName: string;
      /**
       * Whether the legislation expression is currently in force.
       *
       * @enum {string}
       */
      legislationLegalForce: "InForce" | "NotInForce" | "PartiallyInForce";
      encoding: components["schemas"]["LegislationObjectSchema"][];
    });
    LegislationObjectSchema: {
      /**
       * @example
       *   LegislationObject;
       */
      "@type"?: string;
      /**
       * @example
       *   /v1/legislation/eli/bund/bgbl-1/1975/s1760/1998-01-29/10/deu/1998-01-29/regelungstext-1/html
       */
      "@id": string;
      /**
       * @example
       *   /v1/legislation/eli/bund/bgbl-1/1975/s1760/1998-01-29/10/deu/1998-01-29/regelungstext-1.html
       */
      contentUrl: string;
      /**
       * @example
       *   text / html;
       */
      encodingFormat: string;
      /**
       * @example
       *   de;
       */
      inLanguage: string;
    };
    LegislationWorkSchema: {
      /**
       * @example
       *   Legislation;
       */
      "@type"?: string;
      /**
       * @example
       *   /v1/legislation/eli/bund/bgbl-1/1975
       */
      "@id": string;
      /**
       * @example
       *   eli / bund / bgbl - 1 / 1975 / s1760;
       */
      legislationIdentifier: string;
      /**
       * Format: date
       *
       * Ausfertigungsdatum (The date of adoption or signature of the
       * legislation. This is the date at which the text is officially
       * acknowledged to be a legislation, even though it might not even be
       * published or in force.)
       *
       * @example
       *   2003 - 12 - 15;
       */
      legislationDate: string;
      /**
       * Format: date
       *
       * Verkündungsdatum (The date of first publication of the legislation,
       * when it was published in the official gazette. This may be later than
       * the `legislationDate`.)
       *
       * @example
       *   2003 - 12 - 16;
       */
      datePublished: string;
      isPartOf?: components["schemas"]["PublicationIssueSchema"];
    };
    PublicationIssueSchema: {
      /**
       * @example
       *   PublicationIssue;
       */
      "@type"?: string;
      /**
       * @example
       *   BGBL I 2003, 1760
       */
      name: string;
    };
    SearchMemberSchemaLegislationExpressionSearchSchema: {
      /**
       * @example
       *   SearchResult;
       */
      "@type"?: string;
      item: components["schemas"]["LegislationExpressionSearchSchema"];
      textMatches: components["schemas"]["TextMatchSchema"][];
    };
    /** A specific part of a legislation expression */
    LegislationExpressionPartSchema: {
      /**
       * @example
       *   Legislation;
       */
      "@type"?: string;
      /**
       * @example
       *   /v1/legislation/eli/bund/bgbl-1/1975/s1760/regelungstext-1.xml#hauptteitel-para-1
       */
      "@id": string;
      /**
       * Expression-level identifier, uniquely identifying this element in an
       * FRBR expression
       *
       * @example
       *   hauptteitel - para - 1;
       */
      eId: string;
      /**
       * Numerical identifier of a specific legislation part
       *
       * @example
       *   § 1
       */
      name: string;
      /**
       * Headline of a specific legislation part
       *
       * @example
       *   Beginn der Rechtsfähigkeit
       */
      headline: string;
      /**
       * Textual string indicating a time period in [ISO 8601 time interval
       * format](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals)
       *
       * @example
       *   1998-02-06/..
       */
      temporalCoverage: string;
      /** The source data for this part, if available on its own */
      encoding?: components["schemas"]["LegislationObjectSchema"][];
      hasPart?: components["schemas"]["LegislationExpressionPartSchema"][];
    };
    /** A legislation expression and references to its manifestations. */
    LegislationExpressionSchema: {
      /**
       * @example
       *   Legislation;
       */
      "@type"?: string;
      /**
       * @example
       *   /v1/legislation/eli/bund/bgbl-1/1975/s1760/1998-01-29/10/deu
       */
      "@id": string;
      /**
       * Amtliche Langüberschrift
       *
       * @example
       *   Verordnung über Kakao und Kakaoerzeugnisse
       */
      name: string;
      /**
       * Amtliche Buchstabenabkürzung, if it exists. Otherwise ris-abkuerzung.
       *
       * @example
       *   KakaoV 2003
       */
      abbreviation?: string;
      /**
       * Amtliche Kurzüberschrift
       *
       * @example
       *   Kakaoverordnung;
       */
      alternateName: string;
      /** The work the expression is based on */
      exampleOfWork: components["schemas"]["LegislationWorkSchema"];
      /**
       * @example
       *   eli / bund / bgbl - 1 / 1975 / s1760 / 1998 - 01 - 29 / 10 / deu;
       */
      legislationIdentifier: string;
      /**
       * Textual string indicating a time period in [ISO 8601 time interval
       * format](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals)
       *
       * @example
       *   1998-02-06/..
       */
      temporalCoverage: string;
      /**
       * Whether the legislation expression is currently in force.
       *
       * @enum {string}
       */
      legislationLegalForce: "InForce" | "NotInForce" | "PartiallyInForce";
      /**
       * List of components (articles, preambles, conclusions, attachments, …)
       * that form this legislation item.
       */
      hasPart: components["schemas"]["LegislationExpressionPartSchema"][];
      encoding: components["schemas"]["LegislationObjectSchema"][];
    };
    StreamingResponseBody: unknown;
    AbstractDocumentSchema: {
      "@type": string;
    };
    AdministrativeDirectiveEncodingSchema: {
      /**
       * @example
       *   MediaObject;
       */
      "@type"?: string;
      "@id": string;
      contentUrl: string;
      /**
       * @example
       *   text / html;
       */
      encodingFormat: string;
      /**
       * @example
       *   de;
       */
      inLanguage: string;
    };
    AdministrativeDirectiveSearchSchema: {
      "@type": "AdministrativeDirectiveSearchSchema";
    } & (Omit<components["schemas"]["AbstractDocumentSchema"], "@type"> & {
      /**
       * @example
       *   AdministrativeDirective;
       */
      "@type"?: string;
      /**
       * @example
       *   KALU000000000;
       */
      "@id": string;
      /**
       * Dokumentnummer
       *
       * @example
       *   KALU000000000;
       */
      documentNumber: string;
      /** Haupttitel */
      headline?: string;
      /** Kurzreferat */
      shortReport?: string;
      /** Gliederung */
      outline?: string[];
      /**
       * Dokumenttyp
       *
       * @example
       *   VV;
       */
      documentType: string;
      /**
       * Aktenzeichen
       *
       * @example
       *   ["ZZ", "YY"];
       */
      referenceNumbers: string[];
      /** Normgeber */
      legislationAuthority?: string;
      /**
       * Format: date
       *
       * Gültig ab Datum
       *
       * @example
       *   2003 - 12 - 15;
       */
      entryIntoForceDate?: string;
      encoding: components["schemas"]["AdministrativeDirectiveEncodingSchema"][];
    });
    CaseLawEncodingSchema: {
      /**
       * @example
       *   MediaObject;
       */
      "@type"?: string;
      "@id": string;
      contentUrl: string;
      /**
       * @example
       *   text / html;
       */
      encodingFormat: string;
      /**
       * @example
       *   de;
       */
      inLanguage: string;
    };
    CaseLawSearchSchema: {
      "@type": "CaseLawSearchSchema";
    } & (Omit<components["schemas"]["AbstractDocumentSchema"], "@type"> & {
      /**
       * @example
       *   Decision;
       */
      "@type"?: string;
      /**
       * @example
       *   KARE000000000;
       */
      documentNumber: string;
      /**
       * @example
       *   ECLI:DE:FGRLP:1969:0905.IV85.68.0A
       */
      ecli: string;
      /**
       * @example
       *   Überschrift;
       */
      headline?: string;
      /**
       * @example
       *   Sonstiger Langtext
       */
      otherLongText?: string;
      /** Format: date */
      decisionDate: string;
      /**
       * @example
       *   BGH 123/23
       */
      fileNumbers: string[];
      /**
       * @example
       *   FG;
       */
      courtType?: string;
      /**
       * @example
       *   Berlin;
       */
      location?: string;
      /**
       * @example
       *   Urteil;
       */
      documentType?: string;
      /**
       * @example
       *   Leitsatz;
       */
      outline?: string;
      /**
       * @example
       *   Gericht;
       */
      judicialBody?: string;
      /**
       * @example
       *   LArbG Hamm
       */
      courtName?: string;
      /**
       * @example
       *   Beispielentscheidung;
       */
      decisionName: string[];
      /**
       * @example
       *   DEV - 123;
       */
      deviatingDocumentNumber: string[];
      encoding: components["schemas"]["CaseLawEncodingSchema"][];
      /**
       * @example
       *   /v1/case-law/ECLI:DE:FGRLP:1969:0905.IV85.68.0A
       */
      "@id": string;
      /**
       * @example
       *   de;
       */
      inLanguage: string;
    });
    CollectionSchemaSearchMemberSchemaAbstractDocumentSchema: {
      /**
       * @example
       *   hydra: Collection;
       */
      "@type"?: string;
      /**
       * @example
       *   /v1/document?pageIndex=0&size=5
       */
      "@id": string;
      /**
       * Format: int64
       *
       * @example
       *   1;
       */
      totalItems: number;
      member: components["schemas"]["SearchMemberSchemaAbstractDocumentSchema"][];
      view: components["schemas"]["PartialCollectionViewSchema"];
    };
    SearchMemberSchemaAbstractDocumentSchema: {
      /**
       * @example
       *   SearchResult;
       */
      "@type"?: string;
      item:
        | components["schemas"]["AdministrativeDirectiveSearchSchema"]
        | components["schemas"]["CaseLawSearchSchema"]
        | components["schemas"]["LegislationExpressionSearchSchema"]
        | components["schemas"]["LiteratureSearchSchema"];
      textMatches: components["schemas"]["TextMatchSchema"][];
    };
    CollectionSchemaSearchMemberSchemaCaseLawSearchSchema: {
      /**
       * @example
       *   hydra: Collection;
       */
      "@type"?: string;
      /**
       * @example
       *   /v1/document?pageIndex=0&size=5
       */
      "@id": string;
      /**
       * Format: int64
       *
       * @example
       *   1;
       */
      totalItems: number;
      member: components["schemas"]["SearchMemberSchemaCaseLawSearchSchema"][];
      view: components["schemas"]["PartialCollectionViewSchema"];
    };
    SearchMemberSchemaCaseLawSearchSchema: {
      /**
       * @example
       *   SearchResult;
       */
      "@type"?: string;
      item: components["schemas"]["CaseLawSearchSchema"];
      textMatches: components["schemas"]["TextMatchSchema"][];
    };
    CollectionSchemaSearchMemberSchemaAdministrativeDirectiveSearchSchema: {
      /**
       * @example
       *   hydra: Collection;
       */
      "@type"?: string;
      /**
       * @example
       *   /v1/document?pageIndex=0&size=5
       */
      "@id": string;
      /**
       * Format: int64
       *
       * @example
       *   1;
       */
      totalItems: number;
      member: components["schemas"]["SearchMemberSchemaAdministrativeDirectiveSearchSchema"][];
      view: components["schemas"]["PartialCollectionViewSchema"];
    };
    SearchMemberSchemaAdministrativeDirectiveSearchSchema: {
      /**
       * @example
       *   SearchResult;
       */
      "@type"?: string;
      item: components["schemas"]["AdministrativeDirectiveSearchSchema"];
      textMatches: components["schemas"]["TextMatchSchema"][];
    };
    CaseLawSchema: {
      /**
       * @example
       *   Decision;
       */
      "@type"?: string;
      /**
       * @example
       *   KARE000000000;
       */
      documentNumber: string;
      /**
       * European Case Law Identifier
       *
       * @example
       *   ECLI:DE:FGRLP:1969:0905.IV85.68.0A
       */
      ecli: string;
      /** Tatbestand */
      caseFacts?: string;
      /** Entscheidungsgründe */
      decisionGrounds?: string;
      /** Abweichende Meinung */
      dissentingOpinion?: string;
      /** Gründe */
      grounds?: string;
      /** Leitsatz */
      guidingPrinciple?: string;
      /** Überschrift */
      headline?: string;
      /** Orientierungssatz */
      headnote?: string;
      /** Sonstiger Orientierungssatz */
      otherHeadnote?: string;
      /** Sonstiger Langtext */
      otherLongText?: string;
      /** Tenor */
      tenor?: string;
      /**
       * Format: date
       *
       * Entscheidungsdatum
       */
      decisionDate: string;
      /**
       * Aktenzeichen
       *
       * @example
       *   BGH 123/23
       */
      fileNumbers: string[];
      /**
       * Gerichtstyp
       *
       * @example
       *   FG;
       */
      courtType?: string;
      /**
       * Gerichtssitz
       *
       * @example
       *   Berlin;
       */
      location?: string;
      /**
       * @example
       *   Urteil;
       */
      documentType?: string;
      /** Leitsatz */
      outline?: string;
      /**
       * Spruchkörper
       *
       * @example
       *   Gericht;
       */
      judicialBody?: string;
      /**
       * Schlagworte
       *
       * @example
       *   3. Kammer
       */
      keywords: string[];
      /**
       * @example
       *   LArbG Hamm
       */
      courtName?: string;
      /**
       * Entscheidungsname
       *
       * @example
       *   Beispielentscheidung;
       */
      decisionName: string[];
      /**
       * Abweichende Dokumentnummer
       *
       * @example
       *   DEV - 123;
       */
      deviatingDocumentNumber: string[];
      /**
       * @example
       *   /v1/case-law/ECLI:DE:FGRLP:1969:0905.IV85.68.0A
       */
      "@id": string;
      /**
       * @example
       *   de;
       */
      inLanguage: string;
      encoding: components["schemas"]["CaseLawEncodingSchema"][];
    };
    CourtSearchResult: {
      /**
       * @example
       *   BGH Karlsruhe
       */
      id?: string;
      /**
       * Format: int64
       *
       * @example
       *   10000;
       */
      count?: number;
      /**
       * @example
       *   Bundesgerichtshof Karlsruhe
       */
      label?: string;
    };
    /**
     * Represents a <a
     * href="https://schema.org/DataCatalog">schema.org/DataCatalog</a>.
     */
    ZipDataCatalogSchema: {
      /**
       * @example
       *   https://schema.org/
       */
      "@context"?: string;
      /**
       * @example
       *   DataCatalog;
       */
      "@type"?: string;
      /** The name of this data catalog. */
      name: string;
      /** The list of zip datasets contained in this catalog. */
      dataSet: components["schemas"]["ZipDataSetSchema"][];
    };
    /**
     * Represents <a
     * href="https://schema.org/DataDownload">schema.org/DataDownload</a>.
     */
    ZipDataDownloadSchema: {
      /**
       * @example
       *   DataDownload;
       */
      "@type"?: string;
      /** Will always be application/zip. */
      encodingFormat: string;
      /** The url to download the zip file. */
      contentUrl: string;
    };
    /** Represents <a href="https://schema.org/Dataset">schema.org/Dataset</a>. */
    ZipDataSetSchema: {
      /**
       * @example
       *   Dataset;
       */
      "@type"?: string;
      /** The name of the dataset. */
      name: string;
      /** A short summary describing the contents of the dataset. */
      description: string;
      /** The downloadable form of this dataset. */
      distribution?: components["schemas"]["ZipDataDownloadSchema"];
    };
    AdministrativeDirectiveSchema: {
      /**
       * @example
       *   AdministrativeDirective;
       */
      "@type"?: string;
      /**
       * @example
       *   KALU000000000;
       */
      "@id": string;
      /**
       * Dokumentnummer
       *
       * @example
       *   KALU000000000;
       */
      documentNumber: string;
      /** Haupttitel */
      headline?: string;
      /** Kurzreferat */
      shortReport?: string;
      /**
       * Dokumenttyp
       *
       * @example
       *   VV;
       */
      documentType: string;
      /**
       * Art der Verwaltungsvorschrift
       *
       * @example
       *   Bekanntmachung;
       */
      documentTypeDetail?: string;
      /**
       * Aktenzeichen
       *
       * @example
       *   ["ZZ", "YY"];
       */
      referenceNumbers: string[];
      /**
       * Format: date
       *
       * Gültig ab Datum
       *
       * @example
       *   2003 - 12 - 15;
       */
      entryIntoForceDate?: string;
      /**
       * Format: date
       *
       * Gültig bis Datum
       *
       * @example
       *   2005 - 12 - 01;
       */
      expiryDate?: string;
      /** Normgeber */
      legislationAuthority?: string;
      /** Fundstelle */
      references: string[];
      /** Zitierdaten */
      citationDates: string[];
      /**
       * Normkette
       *
       * @example
       *   ["§ 1 Abs1 SGB"];
       */
      normReferences: string[];
      /** Gliederung */
      outline: string[];
      encoding: components["schemas"]["AdministrativeDirectiveEncodingSchema"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getStatisticsData: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatisticsApiSchema"];
        };
      };
    };
  };
  searchAndFilter: {
    parameters: {
      query?: {
        documentNumber?: string;
        yearOfPublication?: string[];
        documentType?: string[];
        author?: string[];
        collaborator?: string[];
        /**
         * Searches for the given tokens in searchTerm. If searchTerm contains
         * more than one token, all tokens must be in the document for the
         * document to match.
         */
        searchTerm?: string;
        /**
         * The from (greater than or equal) parameter returns all entities where
         * date is later than, or equal to, the given date.
         */
        dateFrom?: string;
        /**
         * The to (less than or equal) parameter returns all entities where date
         * is earlier than, or equal to, the given date.
         */
        dateTo?: string;
        /**
         * The number of entities per page
         *
         * @example
         *   100;
         */
        size?: number;
        /**
         * The number of the page to request. The page starts with the value 0
         *
         * @example
         *   0;
         */
        pageIndex?: number;
        /**
         * The field to sort the results by. Default is the relevance score
         * calculated by OpenSearch. Valid usage of the sort field are : date
         * and documentNumber and not setting the sort field (sort by relevance
         * descending).Add a leading - to set the order to descending (-date)
         */
        sort?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CollectionSchemaSearchMemberSchemaLiteratureSearchSchema"];
        };
      };
      /** Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getLiteratureMetadata: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @example
         *   STRE201770751;
         */
        documentNumber: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LiteratureSchema"];
        };
      };
      /** Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getLiteratureAsXml: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @example
         *   BJLU075748788;
         */
        documentNumber: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/xml": string;
        };
      };
      /** Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getLiteratureAsHtml: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @example
         *   BJLU075748788;
         */
        documentNumber: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": string;
        };
      };
      /** Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getChangelogs: {
    parameters: {
      query: {
        from: string;
        to: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ChangelogResponse"];
        };
      };
    };
  };
  searchAndFilter_1: {
    parameters: {
      query?: {
        /**
         * Search by European Legislation Identifier (ELI). Right now only
         * searching by work ELI is supported, but a general eli prefix match
         * might be supported in the future.
         */
        eli?: string;
        /**
         * Filters the result set to only return expressions that are in force
         * _on or after_ the provided date. The parameter should be provided in
         * `YYYY-MM-DD` format. Differs from `dateFrom`, which refers to the
         * date of adoption or signature of the legislation. If both
         * `temporalCoverageFrom` and `temporalCoverageTo` are given, this will
         * output all expressions that were in force during at least one day
         * between the two dates. To get all expressions for one specific day,
         * set both parameters to the same day.
         */
        temporalCoverageFrom?: string;
        /**
         * Filters the result set to only return expressions that are in force
         * _on or before_ the provided date. The parameter should be provided in
         * `YYYY-MM-DD` format. Differs from `dateTo`, which refers to the date
         * of adoption or signature of the legislation.
         */
        temporalCoverageTo?: string;
        /**
         * Filters the result set so every work returns exactly one expression.
         * Most relevant is defined as : The expression in force on that date if
         * it exists, then the expression that would next be in force if that
         * exists, then the most recent expression that was in force. If other
         * filters are used the work may return 0 expressions due to the most
         * relevant expression being filtered out.
         */
        mostRelevantOn?: string;
        /**
         * Searches for the given tokens in searchTerm. If searchTerm contains
         * more than one token, all tokens must be in the document for the
         * document to match.
         */
        searchTerm?: string;
        /**
         * The from (greater than or equal) parameter returns all entities where
         * date is later than, or equal to, the given date.
         */
        dateFrom?: string;
        /**
         * The to (less than or equal) parameter returns all entities where date
         * is earlier than, or equal to, the given date.
         */
        dateTo?: string;
        /**
         * The number of entities per page
         *
         * @example
         *   100;
         */
        size?: number;
        /**
         * The number of the page to request. The page starts with the value 0
         *
         * @example
         *   0;
         */
        pageIndex?: number;
        /**
         * The field to sort the results by. Default is the relevance score
         * calculated by OpenSearch. Valid usage of the sort field are : date,
         * temporalCoverageFrom, legislationIdentifier and not setting the sort
         * field (sort by relevance descending).Add a leading - to set the order
         * to descending (-date)
         */
        sort?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CollectionSchemaSearchMemberSchemaLegislationExpressionSearchSchema"];
        };
      };
      /** Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CollectionSchemaSearchMemberSchemaLegislationExpressionSearchSchema"];
        };
      };
    };
  };
  getLegislation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** Country or regional code for the jurisdiction */
        jurisdiction: "bund";
        /**
         * Agent or authority issuing the legislation, e.g., 'bgbl-1' for
         * Bundesgesetzblatt Teil I (Federal Law Gazette part I)
         *
         * @example
         *   bgbl - 1;
         */
        agent: string;
        /**
         * Year the legislation was enacted or published
         *
         * @example
         *   1979;
         */
        year: string;
        /**
         * Unique natural identifier for the legislation, specific to the
         * jurisdiction and agent
         *
         * @example
         *   s1325;
         */
        naturalIdentifier: string;
        /**
         * @example
         *   2020 - 06 - 19;
         */
        pointInTime: string;
        /**
         * @example
         *   2;
         */
        version: number;
        /**
         * @example
         *   deu;
         */
        language: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LegislationExpressionSchema"];
        };
      };
      /** Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getLegislationArticleAsHtml: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * Country or regional code for the jurisdiction
         *
         * @example
         *   bund;
         */
        jurisdiction: "bund";
        /**
         * Agent or authority issuing the legislation, e.g., 'bgbl-1' for
         * Bundesgesetzblatt Teil I (Federal Law Gazette part I)
         *
         * @example
         *   bgbl - 1;
         */
        agent: string;
        /**
         * Year the legislation was enacted or published
         *
         * @example
         *   1979;
         */
        year: string;
        /**
         * Unique natural identifier for the legislation, specific to the
         * jurisdiction and agent
         *
         * @example
         *   s1325;
         */
        naturalIdentifier: string;
        /**
         * @example
         *   2020 - 06 - 19;
         */
        pointInTime: string;
        /**
         * @example
         *   2;
         */
        version: number;
        /**
         * @example
         *   deu;
         */
        language: string;
        /**
         * @example
         *   2020 - 06 - 19;
         */
        pointInTimeManifestation: string;
        /**
         * @example
         *   regelungstext - 1;
         */
        subtype: string;
        /**
         * The expression identifier, denoting elements inside an expression
         *
         * @example
         *   art - z1;
         */
        articleEid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": string;
        };
      };
      /** Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": string;
        };
      };
    };
  };
  getLegislationSubtypeAsXml: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * Country or regional code for the jurisdiction
         *
         * @example
         *   bund;
         */
        jurisdiction: "bund";
        /**
         * Agent or authority issuing the legislation, e.g., 'bgbl-1' for
         * Bundesgesetzblatt Teil I (Federal Law Gazette part I)
         *
         * @example
         *   bgbl - 1;
         */
        agent: string;
        /**
         * Year the legislation was enacted or published
         *
         * @example
         *   1979;
         */
        year: string;
        /**
         * Unique natural identifier for the legislation, specific to the
         * jurisdiction and agent
         *
         * @example
         *   s1325;
         */
        naturalIdentifier: string;
        /**
         * @example
         *   2020 - 06 - 19;
         */
        pointInTime: string;
        /**
         * @example
         *   2;
         */
        version: number;
        /**
         * @example
         *   deu;
         */
        language: string;
        /**
         * @example
         *   2020 - 06 - 19;
         */
        pointInTimeManifestation: string;
        /**
         * @example
         *   regelungstext - 1;
         */
        subtype: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/xml": string;
        };
      };
      /** Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getLegislationSubtypeAsHtml: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * Country or regional code for the jurisdiction
         *
         * @example
         *   bund;
         */
        jurisdiction: "bund";
        /**
         * Agent or authority issuing the legislation, e.g., 'bgbl-1' for
         * Bundesgesetzblatt Teil I (Federal Law Gazette part I)
         *
         * @example
         *   bgbl - 1;
         */
        agent: string;
        /**
         * Year the legislation was enacted or published
         *
         * @example
         *   1979;
         */
        year: string;
        /**
         * Unique natural identifier for the legislation, specific to the
         * jurisdiction and agent
         *
         * @example
         *   s1325;
         */
        naturalIdentifier: string;
        /**
         * @example
         *   2020 - 06 - 19;
         */
        pointInTime: string;
        /**
         * @example
         *   2;
         */
        version: number;
        /**
         * @example
         *   deu;
         */
        language: string;
        /**
         * @example
         *   2020 - 06 - 19;
         */
        pointInTimeManifestation: string;
        /**
         * @example
         *   regelungstext - 1;
         */
        subtype: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": string;
        };
      };
      /** Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": string;
        };
      };
    };
  };
  getFile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * Country or regional code for the jurisdiction
         *
         * @example
         *   bund;
         */
        jurisdiction: "bund";
        /**
         * Agent or authority issuing the legislation, e.g., 'bgbl-1' for
         * Bundesgesetzblatt Teil I (Federal Law Gazette part I)
         *
         * @example
         *   bgbl - 1;
         */
        agent: string;
        /**
         * Year the legislation was enacted or published
         *
         * @example
         *   1979;
         */
        year: string;
        /**
         * Unique natural identifier for the legislation, specific to the
         * jurisdiction and agent
         *
         * @example
         *   s1325;
         */
        naturalIdentifier: string;
        /**
         * @example
         *   2020 - 06 - 19;
         */
        pointInTime: string;
        /**
         * @example
         *   2;
         */
        version: number;
        /**
         * @example
         *   deu;
         */
        language: string;
        /**
         * @example
         *   2020 - 06 - 19;
         */
        pointInTimeManifestation: string;
        /**
         * @example
         *   image;
         */
        name: string;
        /**
         * @example
         *   jpg;
         */
        extension: "pdf" | "xml" | "jpg" | "gif";
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": string;
        };
      };
      /** Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getLegislationSubtypeAsZip: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * Country or regional code for the jurisdiction
         *
         * @example
         *   bund;
         */
        jurisdiction: "bund";
        /**
         * Agent or authority issuing the legislation, e.g., 'bgbl-1' for
         * Bundesgesetzblatt Teil I (Federal Law Gazette part I)
         *
         * @example
         *   bgbl - 1;
         */
        agent: string;
        /**
         * Year the legislation was enacted or published
         *
         * @example
         *   1979;
         */
        year: string;
        /**
         * Unique natural identifier for the legislation, specific to the
         * jurisdiction and agent
         *
         * @example
         *   s1325;
         */
        naturalIdentifier: string;
        /**
         * @example
         *   2020 - 06 - 19;
         */
        pointInTime: string;
        /**
         * @example
         *   2;
         */
        version: number;
        /**
         * @example
         *   deu;
         */
        language: string;
        /**
         * @example
         *   2020 - 06 - 19;
         */
        pointInTimeManifestation: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": components["schemas"]["StreamingResponseBody"];
        };
      };
      /** Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getChangelogs_1: {
    parameters: {
      query: {
        from: string;
        to: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ChangelogResponse"];
        };
      };
    };
  };
  searchAndFilter_2: {
    parameters: {
      query?: {
        /**
         * Searches for the given tokens in searchTerm. If searchTerm contains
         * more than one token, all tokens must be in the document for the
         * document to match.
         */
        searchTerm?: string;
        /**
         * The from (greater than or equal) parameter returns all entities where
         * date is later than, or equal to, the given date.
         */
        dateFrom?: string;
        /**
         * The to (less than or equal) parameter returns all entities where date
         * is earlier than, or equal to, the given date.
         */
        dateTo?: string;
        /**
         * The field to sort the results by. Default is the relevance score
         * calculated by OpenSearch. Valid usage of the sort field are : date,
         * temporalCoverageFrom, legislationIdentifier, courtName,
         * documentNumber and not setting the sort field (sort by relevance
         * descending).Add a leading - to set the order to descending (-date)
         */
        sort?: string;
        /**
         * The number of entities per page
         *
         * @example
         *   100;
         */
        size?: number;
        /**
         * The number of the page to request. The page starts with the value 0
         *
         * @example
         *   0;
         */
        pageIndex?: number;
        /**
         * Filters the result set so every work returns exactly one expression.
         * Most relevant is defined as : The expression in force on that date if
         * it exists, then the expression that would next be in force if that
         * exists, then the most recent expression that was in force. If other
         * filters are used the work may return 0 expressions due to the most
         * relevant expression being filtered out.
         *
         * @example
         *   2026 - 03 - 11;
         */
        mostRelevantOn?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CollectionSchemaSearchMemberSchemaAbstractDocumentSchema"];
        };
      };
      /** Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  search: {
    parameters: {
      query?: {
        /** The query filter based on Lucene query */
        query?: string;
        /**
         * The number of entities per page
         *
         * @example
         *   100;
         */
        size?: number;
        /**
         * The number of the page to request. The page starts with the value 0
         *
         * @example
         *   0;
         */
        pageIndex?: number;
        /**
         * The field to sort the results by. Default is the relevance score
         * calculated by OpenSearch. Valid usage of the sort field are : date,
         * temporalCoverageFrom, legislationIdentifier, courtName,
         * documentNumber and not setting the sort field (sort by relevance
         * descending).Add a leading - to set the order to descending (-date)
         */
        sort?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CollectionSchemaSearchMemberSchemaAbstractDocumentSchema"];
        };
      };
      /** Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  literatureSearch: {
    parameters: {
      query?: {
        /** The query filter based on Lucene query syntax */
        query?: string;
        /**
         * The number of entities per page
         *
         * @example
         *   100;
         */
        size?: number;
        /**
         * The number of the page to request. The page starts with the value 0
         *
         * @example
         *   0;
         */
        pageIndex?: number;
        /**
         * The field to sort the results by. Default is the relevance score
         * calculated by OpenSearch. Valid usage of the sort field are : date
         * and documentNumber and not setting the sort field (sort by relevance
         * descending).Add a leading - to set the order to descending (-date)
         */
        sort?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CollectionSchemaSearchMemberSchemaLiteratureSearchSchema"];
        };
      };
      /** Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  searchLegislation: {
    parameters: {
      query?: {
        /** The query filter based on Lucene query */
        query?: string;
        /**
         * The number of entities per page
         *
         * @example
         *   100;
         */
        size?: number;
        /**
         * The number of the page to request. The page starts with the value 0
         *
         * @example
         *   0;
         */
        pageIndex?: number;
        /**
         * The field to sort the results by. Default is the relevance score
         * calculated by OpenSearch. Valid usage of the sort field are : date,
         * temporalCoverageFrom, legislationIdentifier and not setting the sort
         * field (sort by relevance descending).Add a leading - to set the order
         * to descending (-date)
         */
        sort?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CollectionSchemaSearchMemberSchemaLegislationExpressionSearchSchema"];
        };
      };
      /** Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  caseLawSearch: {
    parameters: {
      query?: {
        /** The query filter based on Lucene query syntax */
        query?: string;
        /**
         * The number of entities per page
         *
         * @example
         *   100;
         */
        size?: number;
        /**
         * The number of the page to request. The page starts with the value 0
         *
         * @example
         *   0;
         */
        pageIndex?: number;
        /**
         * The field to sort the results by. Default is the relevance score
         * calculated by OpenSearch. Valid usage of the sort field are : date,
         * courtName, documentNumber and not setting the sort field (sort by
         * relevance descending).Add a leading - to set the order to descending
         * (-date)
         */
        sort?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CollectionSchemaSearchMemberSchemaCaseLawSearchSchema"];
        };
      };
      /** Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  literatureSearch_1: {
    parameters: {
      query?: {
        /** The query filter based on Lucene query syntax */
        query?: string;
        /**
         * The number of entities per page
         *
         * @example
         *   100;
         */
        size?: number;
        /**
         * The number of the page to request. The page starts with the value 0
         *
         * @example
         *   0;
         */
        pageIndex?: number;
        /**
         * The field to sort the results by. Default is the relevance score
         * calculated by OpenSearch. Valid usage of the sort field are : date
         * and documentNumber and not setting the sort field (sort by relevance
         * descending).Add a leading - to set the order to descending (-date)
         */
        sort?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CollectionSchemaSearchMemberSchemaAdministrativeDirectiveSearchSchema"];
        };
      };
      /** Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  searchAndFilter_3: {
    parameters: {
      query?: {
        fileNumber?: string;
        ecli?: string;
        /**
         * Filter by court name (Finanzgericht Münster, FG Münster, ArbG Köln)
         * or court type (Finanzgericht, FG, ArbG). Supports both long and short
         * names.
         */
        court?: string;
        /**
         * Corresponds to “Rechtskraft”, meaning that the decision referred to
         * is legally binding.
         */
        legalEffect?: "JA" | "NEIN" | "KEINE_ANGABE" | "FALSCHE_ANGABE";
        /**
         * Filter by document type (Urteil, Versäumnisurteil, Entscheidung
         * etc.). Multiple values may be specified as a comma-separated list or
         * by repeating the parameter.
         */
        type?: string[];
        /**
         * Extended filter by type group. Multiple values may be specified as a
         * comma-separated list or by repeating the parameter.
         */
        typeGroup?: "Urteil" | "Beschluss" | "other";
        /**
         * Searches for the given tokens in searchTerm. If searchTerm contains
         * more than one token, all tokens must be in the document for the
         * document to match.
         */
        searchTerm?: string;
        /**
         * The from (greater than or equal) parameter returns all entities where
         * date is later than, or equal to, the given date.
         */
        dateFrom?: string;
        /**
         * The to (less than or equal) parameter returns all entities where date
         * is earlier than, or equal to, the given date.
         */
        dateTo?: string;
        /**
         * The number of entities per page
         *
         * @example
         *   100;
         */
        size?: number;
        /**
         * The number of the page to request. The page starts with the value 0
         *
         * @example
         *   0;
         */
        pageIndex?: number;
        /**
         * The field to sort the results by. Default is the relevance score
         * calculated by OpenSearch. Valid usage of the sort field are : date,
         * courtName, documentNumber and not setting the sort field (sort by
         * relevance descending).Add a leading - to set the order to descending
         * (-date)
         */
        sort?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CollectionSchemaSearchMemberSchemaCaseLawSearchSchema"];
        };
      };
      /** Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getCaseLaw: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @example
         *   STRE201770751;
         */
        documentNumber: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaseLawSchema"];
        };
      };
      /** Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getImage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @example
         *   BDRE000800001;
         */
        documentNumber: string;
        /**
         * @example
         *   image;
         */
        name: string;
        /**
         * @example
         *   jpg;
         */
        extension: "png" | "jpg" | "jpeg" | "gif" | "wmf" | "emf" | "bitmap";
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": string;
        };
      };
      /** Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getCaseLawDocumentationUnitAsZip: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @example
         *   STRE201770751;
         */
        documentNumber: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": components["schemas"]["StreamingResponseBody"];
        };
      };
      /** Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getCaseLawDocumentationUnitAsXml: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @example
         *   STRE201770751;
         */
        documentNumber: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/xml": string;
        };
      };
      /** Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getCaseLawDocumentationUnitAsHtml: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @example
         *   STRE201770751;
         */
        documentNumber: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": string;
        };
      };
      /** Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getCourts: {
    parameters: {
      query?: {
        prefix?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourtSearchResult"][];
        };
      };
    };
  };
  getChangelogs_2: {
    parameters: {
      query: {
        from: string;
        to: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ChangelogResponse"];
        };
      };
    };
  };
  getBulkZipLinks: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ZipDataCatalogSchema"];
        };
      };
    };
  };
  searchAndFilter_4: {
    parameters: {
      query?: {
        documentNumber?: string;
        /**
         * Searches for the given tokens in searchTerm. If searchTerm contains
         * more than one token, all tokens must be in the document for the
         * document to match.
         */
        searchTerm?: string;
        /**
         * The from (greater than or equal) parameter returns all entities where
         * date is later than, or equal to, the given date.
         */
        dateFrom?: string;
        /**
         * The to (less than or equal) parameter returns all entities where date
         * is earlier than, or equal to, the given date.
         */
        dateTo?: string;
        /**
         * The number of entities per page
         *
         * @example
         *   100;
         */
        size?: number;
        /**
         * The number of the page to request. The page starts with the value 0
         *
         * @example
         *   0;
         */
        pageIndex?: number;
        /**
         * The field to sort the results by. Default is the relevance score
         * calculated by OpenSearch. Valid usage of the sort field are : date
         * and documentNumber and not setting the sort field (sort by relevance
         * descending).Add a leading - to set the order to descending (-date)
         */
        sort?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CollectionSchemaSearchMemberSchemaAdministrativeDirectiveSearchSchema"];
        };
      };
      /** Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getAdministrativeDirectiveMetadata: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @example
         *   KSNR00000;
         */
        documentNumber: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdministrativeDirectiveSchema"];
        };
      };
      /** Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getAdministrativeDirectiveAsXml: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @example
         *   KSNR00000;
         */
        documentNumber: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/xml": string;
        };
      };
      /** Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getAdministrativeDirectiveAsHtml: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @example
         *   KSNR00000;
         */
        documentNumber: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": string;
        };
      };
      /** Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getChangelogs_3: {
    parameters: {
      query: {
        from: string;
        to: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ChangelogResponse"];
        };
      };
    };
  };
}
