swagger:
  server:
    url: "https://ris-portal-staging.dev.tech.digitalservice.dev/"

spring:
  config:
    import:
      - "kubernetes:"
      - "optional:configtree:/etc/secrets/*/"

s3:
  file-storage:
    case-law:
      versionPrefix: "V1/"
