server:
  front-end-url: "https://testphase.rechtsinformationen.bund.de/"
  docs-url: "https://docs.rechtsinformationen.bund.de/"
  cms-url: "https://content-management.ris.bund.de/"

swagger:
  server:
    url: "https://testphase.rechtsinformationen.bund.de/"

spring:
  config:
    import:
      - "kubernetes:"
      - "optional:configtree:/etc/secrets/*/"

s3:
  file-storage:
    case-law:
      versionPrefix: "V1/"
