server:
  front-end-url: "https://testphase.rechtsinformationen.bund.de/"
  docs-url: "https://docs.rechtsinformationen.bund.de/"

swagger:
  server:
    url: "https://testphase.rechtsinformationen.bund.de/"

spring:
  config:
    import:
      - "kubernetes:"
      - "optional:configtree:/etc/secrets/*/"
  cloud:
    kubernetes:
      config:
        fail-fast: true
        sources:
          - name: ris-search-opensearch-prototype-config
          - name: posthog-config

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

# Used for sending feedback to posthog
posthog:
  api-key:
  host:
  feedback-survey-id:

s3:
  file-storage:
    case-law:
      versionPrefix: "V1/"
