# Our convention is that all properties are explicitly in this file. If the property isn't used
# everywhere it is set here with the empty string. Kubernetes import is the only exception to this.

spring:
  profiles:
    # Set the default spring profile to dev. dev is used for local development. All other
    # environments explicitly set a profile and therefore don't use the default.
    default: dev

server:
  port: 8080
  front-end-url: ""
  docs-url: ""
  cms-url: ""
  api-keys: []

rate-limit:
  default:
    requests: 600
    seconds: 60
  feedback:
    requests: 5
    seconds: 60

swagger:
  server:
    url: ""
    description: "RIS API url"

springdoc:
  swagger-ui:
    supportedSubmitMethods: ["get"]
    defaultModelsExpandDepth: -1

opensearch:
  host: "${OPENSEARCH_HOST:localhost}"
  port: 9200
  username: ""
  password: ""
  articles-index-name: articles
  norms-index-name: norms
  caselaws-index-name: caselaws
  literature-index-name: literature
  documents-alias-name: documents
  administrative-directive-index-name: administrative_directive

# bucket-name, access-key-id and secret-access-key are overridden my stackit secrets manager
# versionPrefix is overridden in the respective application-ABC.yaml
s3:
  file-storage:
    norm:
      endpoint: "https://object.storage.eu01.onstackit.cloud"
      bucket-name: ""
      access-key-id: ""
      secret-access-key: ""
      versionPrefix: ""
    case-law:
      endpoint: "https://object.storage.eu01.onstackit.cloud"
      bucket-name: ""
      access-key-id: ""
      secret-access-key: ""
      versionPrefix: ""
    literature:
      endpoint: "https://object.storage.eu01.onstackit.cloud"
      bucket-name: ""
      access-key-id: ""
      secret-access-key: ""
      versionPrefix: ""
    administrative-directive:
      endpoint: "https://object.storage.eu01.onstackit.cloud"
      bucket-name: ""
      access-key-id: ""
      secret-access-key: ""
      versionPrefix: ""
    portal:
      endpoint: "https://object.storage.eu01.onstackit.cloud"
      bucket-name: ""
      access-key-id: ""
      secret-access-key: ""
    public-files:
      endpoint: "https://object.storage.eu01.onstackit.cloud"
      bucket-name: ""
      access-key-id: ""
      secret-access-key: ""

sentry:
  release: "${SENTRY_RELEASE:default_release}"
  environment: "${SENTRY_ENVIRONMENT:}"
  traces-sample-rate: 0.01
  minimum-event-level: "error"

app:
  security:
    # Since the api also hosts the swagger files, this header is used for both the api AND some of the docs pages
    # https://testphase.rechtsinformationen.bund.de is in connect-src so the docs "try it out" can call the api
    csp-header: "default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src data: 'self'; connect-src 'self' https://testphase.rechtsinformationen.bund.de; font-src 'self'; frame-src 'none'; object-src 'none'; media-src 'none';"

logging:
  level:
    de:
      bund:
        digitalservice:
          ris:
            search:
              config:
                httplogs: TRACE
      springframework:
        ws:
          server:
            MessageTracing:
              sent: DEBUG
              received: TRACE
