name: Deploy

on:
  workflow_call:
    inputs:
      container-image-version:
        description: 'The sha which identifies the image'
        required: true
        type: string
      deployment-environment:
        description: 'Environment to deploy to, either "staging" or "uat"'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      id-token: write
    steps:
      - uses: chainguard-dev/actions/setup-gitsign@7440e20e3e0bb180a2f6e330bcd53504e2ac8980
      - name: Deploy backend and frontend images to ${{ inputs.deployment-environment}}
        uses: digitalservicebund/argocd-deploy@4e758f584953506c571951ffcba33d6a6246e856
        with:
          environment: ${{ inputs.deployment-environment}}
          version: ${{ inputs.container-image-version }}
          deploying_repo: ris-search,ris-search/frontend
          infra_repo: neuris-portal-infra
          github_app_id: ${{ secrets.GITOPS_NEURIS_APP_ID }}
          github_app_private_key: ${{ secrets.GITOPS_NEURIS_APP_PRIVATE_KEY }}
          app: ris-portal-${{ inputs.deployment-environment}}
          argocd_pipeline_password: ${{ secrets.ARGOCD_PIPELINE_PASSWORD }}
          argocd_server: ${{ secrets.ARGOCD_SERVER }}
          argocd_sync_timeout: 420