name: Deploy

on:
  workflow_call:
    inputs:
      image-tag:
        description: 'The tag of the image to deploy'
        required: true
        type: string
      deployment-environment:
        description: 'Environment to deploy to, either "staging", "uat", "prod" or "prototype"'
        required: true
        type: string
      argocd-app-name:
        description: 'Name of the argoCD app. If not provided will be "ris-search-<deployment-environment>"'
        required: false
        type: string
jobs:
  deploy-to-STACKIT:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    concurrency:
      # Make sure that the deploy-step is always executed in series (this applies across multiple workflows)
      group: ${{ inputs.deployment-environment }}
    steps:
      - name: Deploy backend and frontend images to ${{ inputs.deployment-environment}}
        uses: digitalservicebund/argocd-deploy@6033da861398e0d7fcffe1b195f8d58f10b62c4e # Use the auth-token branch for STACKIT
        with:
          environment: ${{ inputs.deployment-environment}}
          version: ${{ inputs.image-tag }}
          deploying_repo: ris-search,ris-search/frontend
          infra_repo: ris-search-infra
          github_app_id: ${{ secrets.GITOPS_NEURIS_APP_ID }}
          github_app_private_key: ${{ secrets.GITOPS_NEURIS_APP_PRIVATE_KEY }}
          app: ${{ inputs.argocd-app-name || format('ris-search-{0}', inputs.deployment-environment) }}
          argocd_auth_token: ${{ secrets.ARGOCD_AUTH_TOKEN }}
          argocd_server: ${{ secrets.ARGOCD_SERVER_STACKIT }}

      - name: Send status to Slack
        if: ${{ failure() }}
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 # v1.6.1
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ vars.NEURIS_PORTAL_ALERTS_SLACK_CHANNEL_ID }}