name: Deploy

on:
  workflow_call:
    inputs:
      image-tag:
        description: 'The tag of the image to deploy'
        required: true
        type: string
      deployment-environment:
        description: 'Environment to deploy to, either "staging", "uat" or "prototype"'
        required: true
        type: string
      argocd-app-name:
        description: 'Name of the argoCD app. If not provided will be "ris-portal-<deployment-environment>"'
        required: false
        type: string

jobs:
  # NOTE: After our final switch to STACKIT this step can be removed
  # also the input argocd-app-name won't be needed anymore because in STACKIT
  # the argocd projects follow a consistent naming scheme (ris-search-<environment>)
  deploy-to-OTC:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      id-token: write
    steps:
      - uses: chainguard-dev/actions/setup-gitsign@71714a76c3df10b544595a2294c16649dc3472e5
      - name: Deploy backend and frontend images to ${{ inputs.deployment-environment}}
        uses: digitalservicebund/argocd-deploy@4e758f584953506c571951ffcba33d6a6246e856
        with:
          environment: ${{ inputs.deployment-environment}}
          version: ${{ inputs.image-tag }}
          deploying_repo: ris-search,ris-search/frontend
          infra_repo: neuris-portal-infra
          github_app_id: ${{ secrets.GITOPS_NEURIS_APP_ID }}
          github_app_private_key: ${{ secrets.GITOPS_NEURIS_APP_PRIVATE_KEY }}
          app: ${{ inputs.argocd-app-name || format('ris-portal-{0}', inputs.deployment-environment) }}
          argocd_pipeline_password: ${{ secrets.ARGOCD_PIPELINE_PASSWORD }}
          argocd_server: ${{ secrets.ARGOCD_SERVER }}
          argocd_sync_timeout: 420

  deploy-to-STACKIT:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Deploy backend and frontend images to ${{ inputs.deployment-environment}}
        uses: digitalservicebund/argocd-deploy@auth-token # Use the auth-token branch for STACKIT
        with:
          environment: ${{ inputs.deployment-environment}}
          version: ${{ inputs.image-tag }}
          deploying_repo: ris-search,ris-search/frontend
          infra_repo: ris-search-infra
          github_app_id: ${{ secrets.GITOPS_NEURIS_APP_ID }}
          github_app_private_key: ${{ secrets.GITOPS_NEURIS_APP_PRIVATE_KEY }}
          app: ris-search-${{ inputs.deployment-environment }}
          argocd_auth_token: ${{ secrets.ARGOCD_AUTH_TOKEN }}
          argocd_server: ${{ secrets.ARGOCD_SERVER_STACKIT }}