# NOTE: After our final switch to STACKIT this workflow can be removed
name: Deploy-OTC

on:
  workflow_call:
    inputs:
      image-tag:
        description: 'The tag of the image to deploy'
        required: true
        type: string
      deployment-environment:
        description: 'Environment to deploy to, either "staging", "uat" or "prototype"'
        required: true
        type: string
      argocd-app-name:
        description: 'Name of the argoCD app. If not provided will be "ris-portal-<deployment-environment>"'
        required: false
        type: string
jobs:
  deploy-to-OTC:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && !inputs.skip-OTC-deployment }}
    permissions:
      id-token: write
    steps:
      - name: Deploy backend and frontend images to ${{ inputs.deployment-environment}}
        uses: digitalservicebund/argocd-deploy@f641e07b623c4544d048a302cc16fcb18e7bf190
        with:
          environment: ${{ inputs.deployment-environment}}
          version: ${{ inputs.image-tag }}
          deploying_repo: ris-search,ris-search/frontend
          infra_repo: neuris-portal-infra
          github_app_id: ${{ secrets.GITOPS_NEURIS_APP_ID }}
          github_app_private_key: ${{ secrets.GITOPS_NEURIS_APP_PRIVATE_KEY }}
          app: ${{ inputs.argocd-app-name || format('ris-portal-{0}', inputs.deployment-environment) }}
          argocd_pipeline_password: ${{ secrets.ARGOCD_PIPELINE_PASSWORD }}
          argocd_server: ${{ secrets.ARGOCD_SERVER }}
          argocd_sync_timeout: 420

      - name: Send status to Slack
        if: ${{ failure() }}
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 # v1.6.1
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ vars.NEURIS_PORTAL_ALERTS_SLACK_CHANNEL_ID }}