name: Frontend

on:
  workflow_call:
    inputs:
      image-reference:
        description: "The full image reference (registry/repo:tag) for the frontend image"
        required: true
        type: string
      container-registry:
        description: "Name of the container registry"
        required: false
        type: string
        default: ghcr.io

jobs:
  check-frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: ./frontend/package.json
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: ./frontend/pnpm-lock.yaml
      - name: Install Node modules
        run: pnpm install --frozen-lockfile
        working-directory: ./frontend
      - name: Prepare Nuxt
        run: pnpm run prepare
        working-directory: ./frontend
      - name: Check style
        run: pnpm run style:check
        working-directory: ./frontend
      - name: Run tests with coverage
        run: pnpm run coverage
        working-directory: ./frontend
      - name: Set up SonarCloud
        if: ${{  github.actor != 'dependabot[bot]' }}
        # Third-party action, pin to commit SHA!
        # See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=digitalservicebund
            -Dsonar.projectKey=digitalservicebund_ris-search-frontend
            -Dsonar.projectBaseDir=frontend
            -Dsonar.sources=src
            -Dsonar.javascript.lcov.reportPaths=src/coverage/lcov.info
      - name: Check SonarCloud Quality Gate
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: sonarsource/sonarqube-quality-gate-action@cb3ed20f9fec62b4c3b8ad9e77656c6adaade913
        with:
          scanMetadataReportFile: frontend/.scannerwork/report-task.txt
        timeout-minutes: 3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@868884a79c05c62cab52b4f79832cc3589c91a12
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  audit-licences-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: ./frontend/package.json
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: ./frontend/pnpm-lock.yaml
      - name: Install Node modules
        run: pnpm install --frozen-lockfile
        working-directory: ./frontend
      - name: Run licence scanner
        run: pnpm audit:licences
        working-directory: ./frontend
      - name: Upload licence report
        uses: actions/upload-artifact@v7
        with:
          name: licence-reports-frontend
          retention-days: 3
          path: frontend/frontend-licence-report.csv
      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@868884a79c05c62cab52b4f79832cc3589c91a12
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  frontend-file-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Run Trivy vulnerability file scanner
        # Third-party action, pin to commit SHA!
        # See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        with:
          scan-type: "fs"
          scan-ref: "./frontend"
          skip-dirs: node_modules # See https://github.com/aquasecurity/trivy/issues/1283
          format: "sarif"
          output: "trivy-results.sarif"
          trivyignores: frontend/.trivyignore
      - name: Check Trivy results
        run: |
          if grep -qE 'HIGH|CRITICAL' trivy-results.sarif; then
            echo "Vulnerabilities found"
            echo "### Found vulnerabilities in trivy results" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            RESULT=$(cat trivy-results.sarif | jq -r '[.runs[].results[].message.text] | join("\\n\\n")')
            echo -e $RESULT >> $GITHUB_STEP_SUMMARY
            echo -e $RESULT
            exit 1
          else
            echo "No significant vulnerabilities found"
            exit 0
          fi
      - name: Upload Trivy vulnerability file scanner results
        uses: actions/upload-artifact@v7
        if: ${{ failure() }}
        with:
          name: "trivy-frontend-file-results.sarif"
          path: "trivy-results.sarif"
          if-no-files-found: error

  build-and-upload-image:
    runs-on: ubuntu-latest
    needs:
      - check-frontend
      - audit-licences-frontend
      - frontend-file-scan
    permissions:
      packages: write
      contents: read
    env:
      SENTRY_RELEASE: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Sentry CLI using official script
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          curl -sL https://sentry.io/get-cli/ | bash

      - name: Create Sentry release
        # Create the sentry release before the build step so the sourcemap uploading during the
        # frontend build process can associate the sourcemaps with this release
        # NOTE: only create releases on main!
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          sentry-cli releases new $SENTRY_RELEASE
          sentry-cli releases set-commits --auto $SENTRY_RELEASE
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: Log into container registry
        # Third-party action, pin to commit SHA!
        uses: docker/login-action@9fe7774c8f8ebfade96f0a62aa10f3882309d517
        with:
          registry: ${{ inputs.container-registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build frontend image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          file: frontend/Dockerfile
          context: frontend
          tags: ${{ inputs.image-reference }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NUXT_PUBLIC_SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            SENTRY_RELEASE=${{ env.SENTRY_RELEASE }}
          secrets: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Finalize Sentry release
        # NOTE: only on main!
        if: ${{ github.ref == 'refs/heads/main' }}
        run: sentry-cli releases finalize $SENTRY_RELEASE
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Send status to Slack
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        uses: digitalservicebund/notify-on-failure-gha@868884a79c05c62cab52b4f79832cc3589c91a12
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  scan-and-attest-image:
    needs: build-and-upload-image
    uses: ./.github/workflows/attest-image.yml
    secrets: inherit
    with:
      image-reference: ${{ inputs.image-reference }}
      app: frontend

  sign-image:
    runs-on: ubuntu-latest
    needs:
      - scan-and-attest-image
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Log into container registry
        # Third-party action, pin to commit SHA!
        uses: docker/login-action@9fe7774c8f8ebfade96f0a62aa10f3882309d517
        with:
          registry: ${{ inputs.container-registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cosign
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: sigstore/cosign-installer@ba7bc0a3fef59531c69a25acd34668d6d3fe6f22
        with:
          cosign-release: "v2.6.0" # We need to use v2.X.X because of major version GHA v4.X.X and broken image verification of Kyverno

      - name: Sign the published Docker image
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: cosign sign --yes ${{ inputs.image-reference }}

      - name: Send status to Slack
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        uses: digitalservicebund/notify-on-failure-gha@868884a79c05c62cab52b4f79832cc3589c91a12
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

