name: Frontend

on:
  workflow_call:
    inputs:
      image-reference:
        description: "The full image reference (registry/repo:tag) for the frontend image"
        required: true
        type: string
      container-registry:
        description: "Name of the container registry"
        required: false
        type: string
        default: ghcr.io

jobs:
  check-frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          package_json_file: ./frontend/package.json
      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: ./frontend/pnpm-lock.yaml
      - name: Install Node modules
        run: pnpm install --frozen-lockfile
        working-directory: ./frontend
      - name: Prepare Nuxt
        run: pnpm run prepare
        working-directory: ./frontend
      - name: Check style
        run: pnpm run style:check
        working-directory: ./frontend
      - name: Run tests with coverage
        run: pnpm run coverage
        working-directory: ./frontend
      - name: Set up SonarCloud
        if: ${{  github.actor != 'dependabot[bot]' }}
        # Third-party action, pin to commit SHA!
        # See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
        uses: sonarsource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=digitalservicebund
            -Dsonar.projectKey=digitalservicebund_ris-search-frontend
            -Dsonar.projectBaseDir=frontend
            -Dsonar.sources=src
            -Dsonar.javascript.lcov.reportPaths=src/coverage/lcov.info
      - name: Check SonarCloud Quality Gate
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: sonarsource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b # v1.2.0
        with:
          scanMetadataReportFile: frontend/.scannerwork/report-task.txt
        timeout-minutes: 3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 # v1.6.1
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ vars.NEURIS_PORTAL_ALERTS_SLACK_CHANNEL_ID }}

  audit-licences-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          package_json_file: ./frontend/package.json
      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: ./frontend/pnpm-lock.yaml
      - name: Install Node modules
        run: pnpm install --frozen-lockfile
        working-directory: ./frontend
      - name: Run licence scanner
        run: pnpm audit:licences
        working-directory: ./frontend
      - name: Upload licence report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: licence-reports-frontend
          retention-days: 3
          path: frontend/frontend-licence-report.csv
      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 # v1.6.1
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ vars.NEURIS_PORTAL_ALERTS_SLACK_CHANNEL_ID }}

  frontend-file-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run Trivy vulnerability file scanner
        # Third-party action, pin to commit SHA!
        # See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 #v0.35.0
        with:
          scan-type: "fs"
          scan-ref: "./frontend"
          skip-dirs: node_modules # See https://github.com/aquasecurity/trivy/issues/1283
          format: "sarif"
          output: "trivy-results.sarif"
          trivyignores: frontend/.trivyignore
      - name: Check Trivy results
        run: |
          if grep -qE 'HIGH|CRITICAL' trivy-results.sarif; then
            echo "Vulnerabilities found"
            echo "### Found vulnerabilities in trivy results" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            RESULT=$(cat trivy-results.sarif | jq -r '[.runs[].results[].message.text] | join("\\n\\n")')
            echo -e $RESULT >> $GITHUB_STEP_SUMMARY
            echo -e $RESULT
            exit 1
          else
            echo "No significant vulnerabilities found"
            exit 0
          fi
      - name: Upload Trivy vulnerability file scanner results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ failure() }}
        with:
          name: "trivy-frontend-file-results.sarif"
          path: "trivy-results.sarif"
          if-no-files-found: error

  build-and-push-image:
    runs-on: ubuntu-latest
    needs:
      - check-frontend
      - audit-licences-frontend
      - frontend-file-scan
    permissions:
      packages: write
      contents: read
    env:
      SENTRY_RELEASE: ${{ github.sha }}
    outputs:
      image-digest: ${{ steps.docker-build-push.outputs.digest }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Install Sentry CLI using official script
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          curl -sL https://sentry.io/get-cli/ | bash

      - name: Create Sentry release
        # Create the sentry release before the build step so the sourcemap uploading during the
        # frontend build process can associate the sourcemaps with this release
        # NOTE: only create releases on main!
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          sentry-cli releases new $SENTRY_RELEASE
          sentry-cli releases set-commits --auto $SENTRY_RELEASE
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Log into container registry
        # Third-party action, pin to commit SHA!
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ${{ inputs.container-registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build frontend image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        id: docker-build-push
        with:
          file: frontend/Dockerfile
          context: frontend
          tags: ${{ inputs.image-reference }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NUXT_PUBLIC_SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            SENTRY_RELEASE=${{ env.SENTRY_RELEASE }}
          secrets: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Finalize Sentry release
        # NOTE: only on main!
        if: ${{ github.ref == 'refs/heads/main' }}
        run: sentry-cli releases finalize $SENTRY_RELEASE
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Send status to Slack
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 # v1.6.1
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ vars.NEURIS_PORTAL_ALERTS_SLACK_CHANNEL_ID }}

  scan-attest-and-sign-image:
    needs: build-and-push-image
    uses: ./.github/workflows/scan-attest-sign-image.yml
    secrets: inherit
    with:
      # Use image digest instead of tag to uniquely identify the image
      image-reference: ${{ inputs.container-registry}}/${{ github.repository }}/frontend@${{ needs.build-and-push-image.outputs.image-digest }}
      app: frontend


