name: CI-CD-Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow to run this workflow manually
  workflow_dispatch:

env:
  RUN_ID: ${{ github.run_id }}

jobs:
  e2e-tests:
    uses: ./.github/workflows/pipeline-e2e.yml
    secrets: inherit

  backend-jobs:
    uses: ./.github/workflows/backend.yml
    secrets: inherit
    with:
      container-registry: ghcr.io
      image-reference: ghcr.io/${{ github.repository }}:${{ github.sha }}

  frontend-jobs:
    uses: ./.github/workflows/frontend.yml
    secrets: inherit
    with:
      container-registry: ghcr.io
      image-reference: ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}

  deploy-staging:
    needs:
      - backend-jobs
      - frontend-jobs
      - e2e-tests
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      image-tag: ${{ github.sha }}
      deployment-environment: staging

  smoke-tests:
    needs:
      - deploy-staging
    uses: ./.github/workflows/smoke-tests.yml
    secrets: inherit

  deploy-uat:
    needs:
      - smoke-tests
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      container-image-version: ${{ github.sha }}
      deployment-environment: uat

  deploy-prototype:
    needs:
      - deploy-uat
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      container-image-version: ${{ github.sha }}
      deployment-environment: prototype
      argocd-app-name: ris-portal-prototype-production