name: CI-CD-Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow to run this workflow manually
  workflow_dispatch:

env:
  RUN_ID: ${{ github.run_id }}

jobs:
  e2e-tests:
    uses: ./.github/workflows/pipeline-e2e.yml
    secrets: inherit

  backend-jobs:
    uses: ./.github/workflows/backend.yml
    secrets: inherit
    with:
      container-registry: ghcr.io
      image-reference: ghcr.io/${{ github.repository }}:${{ github.sha }}

  frontend-jobs:
    uses: ./.github/workflows/frontend.yml
    secrets: inherit
    with:
      container-registry: ghcr.io
      image-reference: ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}

  deploy-staging:
    needs:
      - backend-jobs
      - frontend-jobs
      - e2e-tests
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      image-tag: ${{ github.sha }}
      deployment-environment: staging

  smoke-tests:
    needs:
      - deploy-staging
    uses: ./.github/workflows/smoke-tests.yml
    secrets: inherit

  deploy-uat:
    needs:
      - smoke-tests
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      image-tag: ${{ github.sha }}
      deployment-environment: uat

  deploy-prototype:
    needs:
      - deploy-uat
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      image-tag: ${{ github.sha }}
      deployment-environment: prototype
      argocd-app-name: ris-portal-prototype-production

  # Note: This is not using the reusable deploy.yml workflow
  # because the environment ("prod") string and the app postfix
  # "production" are not the same and this would require yet another
  # workaround with inputs. As we plan to remove the otc deployments
  # in the near future, this can be refactored at that point.
  deploy-production-to-STACKIT:
    needs: deploy-prototype
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Deploy backend and frontend images to production on STACKIT
        uses: digitalservicebund/argocd-deploy@auth-token # Use the auth-token branch for STACKIT
        with:
          environment: prod
          version: ${{ github.sha }}
          deploying_repo: ris-search,ris-search/frontend
          infra_repo: ris-search-infra
          github_app_id: ${{ secrets.GITOPS_NEURIS_APP_ID }}
          github_app_private_key: ${{ secrets.GITOPS_NEURIS_APP_PRIVATE_KEY }}
          app: ris-search-production
          argocd_auth_token: ${{ secrets.ARGOCD_AUTH_TOKEN }}
          argocd_server: ${{ secrets.ARGOCD_SERVER_STACKIT }}

      - name: Send status to Slack
        if: ${{ failure() }}
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}