name: End-to-end tests

on:
  workflow_call:
    secrets:
      REPORTS_BUCKET_ACCESS_KEY_ID:
        required: true
      REPORTS_BUCKET_SECRET_ACCESS_KEY:
        required: true
      SLACK_BOT_TOKEN:
        required: true
  workflow_dispatch:

permissions:
  contents: read
  packages: read

env:
  RUN_ID: ${{ github.run_id }}

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container:
      # Image version must match @playwright/test in frontend/package.json
      image: mcr.microsoft.com/playwright@sha256:5b8f294aff9041b7191c34a4bab3ac270157a28774d4b0660e9743297b697e48 # v1.61.1-noble
      options: --user 1001
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        configuration_label: [prototype, private]
        browser: [chromium, firefox, mobile]
        include:
          - configuration_label: prototype
            private_features_enabled: false
          - configuration_label: private
            private_features_enabled: true
    services:
      opensearch:
        image: opensearchproject/opensearch@sha256:2f49c399988df5c9a3b25a05ec78ea75ac4b39ae76e1d2609f94a653224bb24b # v2.11.0
        env:
          node.name: opensearch-node1
          discovery.type: single-node
          DISABLE_SECURITY_PLUGIN: "true"
          OPENSEARCH_JAVA_OPTS: "-Xms1024m -Xmx1024m"
        options: >-
          --health-cmd "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"
          --health-interval 5s
          --health-retries 20
          --health-timeout 3s
          --health-start-period 10s
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5
        with:
          java-version: "21.0"
          distribution: "temurin"

      - name: Cache Gradle packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v5
        with:
          path: .gradle-cache
          key: gradle-${{ runner.os }}-${{ hashFiles('backend/**/*.gradle*', 'backend/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        working-directory: ./backend
        run: chmod +x gradlew

      - name: Start backend locally (background)
        working-directory: ./backend
        env:
          SPRING_PROFILES_ACTIVE: e2e,default
          OPENSEARCH_HOST: opensearch # use service name because it's inside the docker network
          GRADLE_USER_HOME: ${{ github.workspace }}/.gradle-cache
          THC_PORT: 8090
          NODE_OPTIONS: "--max_old_space_size=4096"
          GH_PACKAGES_REPOSITORY_USER: ${{ github.actor }}
          GH_PACKAGES_REPOSITORY_TOKEN: ${{ github.token }}
        run: |
          nohup ./gradlew bootRun --no-daemon > backend.log 2>&1 &

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 #v6.0.9
        with:
          package_json_file: ./frontend/package.json

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: ./frontend/package.json
          cache: "pnpm"
          cache-dependency-path: ./frontend/pnpm-lock.yaml

      - name: Install Node modules
        run: pnpm ci
        working-directory: ./frontend

      - name: Start frontend locally (background)
        working-directory: ./frontend
        env:
          NUXT_PUBLIC_PRIVATE_FEATURES_ENABLED: ${{ matrix.private_features_enabled }}
          NUXT_PUBLIC_RIS_BACKEND_URL: http://localhost:8090
          SENTRY_TELEMETRY: false
          CI: true
        run: |
          nohup pnpm dev --no-devtools --port 3000 > frontend.log 2>&1 &

      - name: Wait for backend to respond
        run: |
          echo "Waiting for backend on http://localhost:8090/actuator/health ..."
          until curl --silent --fail http://localhost:8090/actuator/health; do
            echo "Still waiting..."
            sleep 5
          done

      - name: Wait for frontend to fully render
        timeout-minutes: 5
        run: |
          echo "Waiting for Nuxt frontend to render HTML..."
          until curl -s http://localhost:3000 | grep -q 'id="__nuxt"'; do
            echo "Still waiting for Nuxt..."
            sleep 5
          done
          echo "Nuxt is ready!"

      - name: Run Playwright tests
        run: pnpm exec playwright test --project ${{ matrix.browser }}
        working-directory: ./frontend
        env:
          NUXT_PUBLIC_PRIVATE_FEATURES_ENABLED: ${{ matrix.private_features_enabled }}
          TZ: Europe/Berlin

      - name: Upload test reports
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ !failure() }}
        with:
          name: playwright-e2e-tests-report-${{ matrix.configuration_label }}-${{ matrix.browser }}
          path: frontend/playwright-report/**
          retention-days: 5

      - name: Upload traces of failed tests
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ failure() }}
        with:
          name: failed-e2e-tests-${{ matrix.configuration_label }}-${{ matrix.browser }}
          path: frontend/playwright-report/**/*.zip
          retention-days: 5

      - name: Upload backend log
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ failure() }}
        with:
          name: backend-log-${{ matrix.configuration_label }}-${{ matrix.browser }}
          path: backend/backend.log

      - name: Upload frontend log
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ failure() }}
        with:
          name: frontend-log-${{ matrix.configuration_label }}-${{ matrix.browser }}
          path: frontend/frontend.log

      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 # v1.6.1
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ vars.NEURIS_PORTAL_ALERTS_SLACK_CHANNEL_ID }}

  push-reports:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs:
      - e2e-tests
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: E2E test reports - Download
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          path: tmp/playwright-report/
          pattern: playwright-e2e-tests-report-*

      - name: Upload test reports to ris-reports
        uses: digitalservicebund/add-ris-report@5980f8dc97ec0aea58656e79e391eea59a9dfea8
        with:
          filePath: tmp/playwright-report/
          destinationDir: test-reports/ris-search
          reportIsDirectory: true
          BUCKET_ACCESS_KEY_ID: ${{ secrets.REPORTS_BUCKET_ACCESS_KEY_ID }}
          BUCKET_SECRET_ACCESS_KEY: ${{ secrets.REPORTS_BUCKET_SECRET_ACCESS_KEY }}

      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 # v1.6.1
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ vars.NEURIS_PORTAL_ALERTS_SLACK_CHANNEL_ID }}
