name: Update-Chainguard-Image-Version-Cronjob
on:
  # Allow manual workflow trigger
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  update-chainguard-image-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
        - uses: chainguard-dev/actions/setup-gitsign@e1c4977ad9cb32b12c5b222ec0134a22bec60bd5 #v1.6.25

        - name: Bump chainguard/jre image
          uses: digitalservicebund/bump-chainguard-digest@5cef1778a56ae77fec46e2975f767a6a91049edf # v1.1.3
          with:
            image_name: jre
            file_path: backend/Dockerfile.prod
            github_token: ${{ github.token }}
            branch: bump-chaingurad-jre-image-version

        - name: Bump chainguard/nginx image
          uses: digitalservicebund/bump-chainguard-digest@5cef1778a56ae77fec46e2975f767a6a91049edf # v1.1.3
          with:
            image_name: nginx
            file_path: api-docs/Dockerfile
            github_token: ${{ github.token }}
            branch: bump-chaingurad-nginx-image-version

        - name: Bump chainguard/node image
          uses: digitalservicebund/bump-chainguard-digest@5cef1778a56ae77fec46e2975f767a6a91049edf # v1.1.3
          with:
            image_name: node
            file_path: frontend/Dockerfile
            github_token: ${{ github.token }}
            branch: bump-chaingurad-node-image-version

        - name: Send status to Slack
          uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 # v1.6.1
          if: ${{ failure() && github.ref == 'refs/heads/main' }}
          with:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
            SLACK_CHANNEL_ID: ${{ vars.NEURIS_PORTAL_ALERTS_SLACK_CHANNEL_ID }}