name: Update-Chainguard-Image-Version-Cronjob
on:
  schedule:
    - cron: '0 18 * * 0' # Runs at 6:00pm UTC (7 winter time/8 summer time in Germany) on Sundays
  # Allow manual workflow trigger
  workflow_dispatch:

jobs:
  update-chainguard-image-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
        - uses: chainguard-dev/actions/setup-gitsign@de68b87302e6266db5fb5220246f8aa46fe94b67 #v1.6.14
        - name: Bump chainguard/jre image
          uses: digitalservicebund/bump-chainguard-digest@937cc7a12750bfd06419f32cabcaa79a37f32705 # v1.1.3
          with:
            image_name: jre
            file_path: backend/Dockerfile.prod
            github_token: ${{ github.token }}
            branch: bump-chaingurad-jre-image-version